[package]
name = "telephone_booth"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "telephone_booth"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
phonenumber = "0.3.1+8.12.9"
rustler = "0.22.0-rc.0"
